### ISSUE TITLE
blocktime or timestamp?

### ISSUE THREAD

**Issue by shogochiai** [levelkdev/futarchy-app#103]
Calling this one as blocktime is somehow misleading maybe?
https://github.com/levelkdev/futarchy-app/blob/master/contracts/Futarchy.sol#L170

Sorry for nit picking, just for suggestion.

P.S. I'm really excited for this proj. keep watching :)

**Comment by mikec** [comment]
hey @shogochiai! yes, not necessarily the best naming here. Bigger issue is that we weren't able to get the actual latest block timestamp in our web app via the [Aragon API](https://hack.aragon.org/docs/api-intro). I haven't dug into this in a while, do you know if there's now a way we can remove this workaround and use the API?

**Comment by emaG3m** [comment]
#123
