### ISSUE TITLE
Hardcoded IPFS hash?

### ISSUE THREAD

**Issue by bingen** [levelkdev/futarchy-app#107]
What's this hash and why is it hardcoded?

https://github.com/levelkdev/futarchy-app/blob/master/contracts/Futarchy.sol#L112

```
Oracle(priceOracleFactory.createOracle("QmWmyoMoctfbAaiEs2G46gpeUmhqFRDW6KWo64y5r581Vz", priceResolutionDate)),
```

**Comment by emaG3m** [comment]
We're hoping to get rid of this oracle altogether once we switch to the oracle manager. We'll leave this open for now though.

**Comment by emaG3m** [comment]
https://github.com/levelkdev/futarchy-app/pull/136
