### ISSUE TITLE
My positions doesn't work if not connected

### ISSUE THREAD

**Issue by bingen** [levelkdev/futarchy-app#108]
It makes sense, as the app doesn't know the address, but it would be nice to have an error message. Right now it's just a blank screen:

![Screenshot from 2019-05-09 09-47-11](https://user-images.githubusercontent.com/701095/57436306-b82d6680-723f-11e9-8a36-9a531f12c19c.png)

**Comment by emaG3m** [comment]
we were hoping to take this a step further and notify the user whenever they're logged into a separate network than the Dapp. Is this possible within an aragon app to check the network of metamask?

**Comment by sohkai** [comment]
Seeing as you're on using `@aragon/api@1.1.0`, yes, this is available.

- Get the network: [`app.network()`](https://github.com/aragon/aragon.js/blob/master/packages/aragon-api/src/index.js#L48)
	- This is an observable but really will only ever emit one value for now
- Get the connected accounts: [`app.accounts()`](https://github.com/aragon/aragon.js/blob/master/packages/aragon-api/src/index.js#L35)
	- This will emit every time the user changes their account

**Comment by emaG3m** [comment]
#118

**Comment by emaG3m** [comment]
Fixed in #118
