### ISSUE TITLE
MarketCircles (I think?) should be unselectable

### ISSUE THREAD

**Issue by sohkai** [levelkdev/futarchy-app#114]
<img width="188" alt="Screen Shot 2019-05-09 at 10 51 19 AM" src="https://user-images.githubusercontent.com/4166642/57440524-7654ee00-7248-11e9-93b4-1da8c6810b09.png">

The text in these circles should be unselectable (easily done via [`unselectable`](https://github.com/aragon/aragon-ui/blob/master/src/utils/styles/index.js#L6)).

**Comment by mikec** [comment]
fixed by https://github.com/levelkdev/futarchy-app/pull/120
