### ISSUE TITLE
Gain/loss should be 0 if I have no tokens

### ISSUE THREAD

**Issue by sohkai** [levelkdev/futarchy-app#115]
<img width="1201" alt="Screen Shot 2019-05-09 at 10 53 33 AM" src="https://user-images.githubusercontent.com/4166642/57440719-d055b380-7248-11e9-93c2-f882c793e2cc.png">

This isn't wrong, but it seems a bit weird. If I have 0 tokens, my gain/loss should also be 0... right?

**Comment by emaG3m** [comment]
#122
