### ISSUE TITLE
buyMarketPositions fails with high numbers

### ISSUE THREAD

**Issue by mikec** [levelkdev/futarchy-app#128]
![image](https://user-images.githubusercontent.com/3124707/58508148-618dbb00-8161-11e9-9fa2-422f681ed9cb.png)

looks like js `e+` notation for large numbers is breaking for TKN amounts above single digits

**Comment by emaG3m** [comment]
haven't investigated this specific issue yet, but `parseInt` was giving me problems doing calculations with `e+` notation. We're interested in a bigger effort to switch from integers to `BigNumber` right? Could be a part of that unless we want a quick fix here.

**Comment by emaG3m** [comment]
https://github.com/levelkdev/futarchy-app/pull/151
