### ISSUE TITLE
ENOLOCAL when npm i from master

### ISSUE THREAD

**Issue by 0xGabi** [levelkdev/futarchy-app#133]
I got this message: 
```
Could not install from "node_modules/ganache-core/node_modules/web3-providers-ws/websocket@git:/github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2" as it does not contain a package.json file.
```

I fixed it deleting `package-lock.json`

**Comment by emaG3m** [comment]
could not reproduce, but updated `package-lock.json`, hopefully this resolves the issue!
https://github.com/levelkdev/futarchy-app/commit/ef90d8958cb50222f4fca4418928c8d76e85f7e1
